stages:
  - build
  
buildJob:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:7.0
  
  script:
    - dotnet publish -f="net7.0" -c Release -o Artifacts MelissaNameObjectLinuxDotnet/MelissaNameObjectLinuxDotnet.csproj

  artifacts:
    paths:
      - Artifacts/
    expire_in: 1 week
    
  tags:
    - docker-linux
